<!DOCTYPE html>
<html lang="en">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
<title>Page Not Found</title>
<?php
// Important:
//
// to translate this page you should use
// translate helper e.g. $this->translate('Page Not Found').
//
?>
<style type="text/css">
body { 
    color: #777575 !important;
    margin:0 !important;
    padding:20px !important;
    font-family:Arial,Verdana,sans-serif !important;
    font-weight:normal;
}
h1, h2, h3, h4 {
    margin: 0;
    padding: 0;
    font-weight: normal;
    line-height:48px;
}
</style>
</head>
<body>
<h1>Page Not Found</h1>
<h3>The page you are looking for could not be found</h3>
</body>
</html>