<!DOCTYPE html>
<html lang="en">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
<title>Error</title>
<?php
// Important:
//
// to translate this page you should use
// translate helper e.g. echo $this->translate('Error').
//
?>
<style type="text/css">
body { 
    color: #777575 !important;
    margin:0 !important;
    padding:20px !important;
    font-family:Arial,Verdana,sans-serif !important;
    font-weight:normal;
}
h1, h2, h3, h4 {
    margin: 0;
    padding: 0;
    font-weight: normal;
    line-height:48px;
}
dt {
    float: left;
    clear: left;
    text-align: right;
    font-weight: bold;
}
dt::after {
    content: ":";
}
dd {
    margin: 0 0 0 100px;
    padding: 0 0 0.4em 0;
}
</style>
</head>
<body>
<?php if (empty($this->exception) || false == $this->isDevelopmentMode) { ?>
    <h1>Error</h1>
    <h3>An error was encountered</h3>
<?php } else { ?>
    <h1><?php echo get_class($exception) ?></h1>
    <section>
        <dl>
        <?php if ($message = $exception->getMessage()) { ?>
                <dt>Message</dt><dd><?php echo $message ?></dd>
        <?php } ?>
        <?php if ($code = $exception->getCode()) { ?>
                <dt>Code</dt><dd><?php echo $code ?></dd>
        <?php } ?>
        <?php if ($file = $exception->getFile()) { ?> 
                <dt>File</dt><dd><?php echo $file ?></dd>
        <?php } ?>
        <?php if ($line = $exception->getLine()) { ?>
                <dt>Line</dt><dd><?php echo $line ?></dd>
        <?php } ?>
        </dl>
    </section>
    <section>
        <?php if ($trace = $exception->getTraceAsString()) { ?>
            <h2>Trace</h2>
            <pre><?php echo htmlentities($trace) ?></pre>
        <?php } ?>
    </section>
<?php } ?>
</body>
</html>